# Compound Arithmetic and Assignment

Compound arithmetic and assignment statements combine an arithmetic
operation and assignment,

```
 x = x op y;
```

replacing them with the compound form

```
 x op= y;
```

For example, `x = x + 1` may be replaced with `x += 1`.

The signatures of the supported compound arithmetic and assignment
operations are as follows.

```{r results='asis', echo=FALSE}
if (knitr::is_html_output()) {
cat(' * <a href="compound-addition-and-assignment.html">Compound Addition and Assignment</a>\n')
cat(' * <a href="compound-subtraction-and-assignment.html">Compound Subtraction and Assignment</a>\n')
cat(' * <a href="compound-multiplication-and-assignment.html">Compound Multiplication and Assignment</a>\n')
cat(' * <a href="compound-division-and-assignment.html">Compound Division and Assignment</a>\n')
cat(' * <a href="compound-elementwise-multiplication-and-assignment.html">Compound Elementwise Multiplication and Assignment</a>\n')
cat(' * <a href="compound-elementwise-division-and-assignment.html">Compound Elementwise Division and Assignment</a>\n')
}
```

## Compound Addition and Assignment

<!-- void; operator+=; (int x, int y); -->
\index{{\tt \bfseries operator\_compound\_add}!{\tt (int x, int y): void}|hyperpage}

`void` **`operator+=`**`(int x, int y)`<br>\newline
`x += y` is equivalent to `x = x + y`.

<!-- void; operator+=; (real x, real y); -->
\index{{\tt \bfseries operator\_compound\_add}!{\tt (real x, real y): void}|hyperpage}

`void` **`operator+=`**`(real x, real y)`<br>\newline
`x += y` is equivalent to `x = x + y`.

<!-- void; operator+=; (vector x, real y); -->
\index{{\tt \bfseries operator\_compound\_add}!{\tt (vector x, real y): void}|hyperpage}

`void` **`operator+=`**`(vector x, real y)`<br>\newline
`x += y` is equivalent to `x = x + y`.

<!-- void; operator+=; (row_vector x, real y); -->
\index{{\tt \bfseries operator\_compound\_add}!{\tt (row\_vector x, real y): void}|hyperpage}

`void` **`operator+=`**`(row_vector x, real y)`<br>\newline
`x += y` is equivalent to `x = x + y`.

<!-- void; operator+=; (matrix x, real y); -->
\index{{\tt \bfseries operator\_compound\_add}!{\tt (matrix x, real y): void}|hyperpage}

`void` **`operator+=`**`(matrix x, real y)`<br>\newline
`x += y` is equivalent to `x = x + y`.

<!-- void; operator+=; (vector x, vector y); -->
\index{{\tt \bfseries operator\_compound\_add}!{\tt (vector x, vector y): void}|hyperpage}

`void` **`operator+=`**`(vector x, vector y)`<br>\newline
`x += y` is equivalent to `x = x + y`.

<!-- void; operator+=; (row_vector x, row_vector y); -->
\index{{\tt \bfseries operator\_compound\_add}!{\tt (row\_vector x, row\_vector y): void}|hyperpage}

`void` **`operator+=`**`(row_vector x, row_vector y)`<br>\newline
`x += y` is equivalent to `x = x + y`.

<!-- void; operator+=; (matrix x, matrix y); -->
\index{{\tt \bfseries operator\_compound\_add}!{\tt (matrix x, matrix y): void}|hyperpage}

`void` **`operator+=`**`(matrix x, matrix y)`<br>\newline
`x += y` is equivalent to `x = x + y`.

## Compound Subtraction and Assignment

<!-- void; operator-=; (int x, int y); -->
\index{{\tt \bfseries operator\_compound\_subtract}!{\tt (int x, int y): void}|hyperpage}

`void` **`operator-=`**`(int x, int y)`<br>\newline
`x -= y` is equivalent to `x = x - y`.

<!-- void; operator-=; (real x, real y); -->
\index{{\tt \bfseries operator\_compound\_subtract}!{\tt (real x, real y): void}|hyperpage}

`void` **`operator-=`**`(real x, real y)`<br>\newline
`x -= y` is equivalent to `x = x - y`.

<!-- void; operator-=; (vector x, real y); -->
\index{{\tt \bfseries operator\_compound\_subtract}!{\tt (vector x, real y): void}|hyperpage}

`void` **`operator-=`**`(vector x, real y)`<br>\newline
`x -= y` is equivalent to `x = x - y`.

<!-- void; operator-=; (row_vector x, real y); -->
\index{{\tt \bfseries operator\_compound\_subtract}!{\tt (row\_vector x, real y): void}|hyperpage}

`void` **`operator-=`**`(row_vector x, real y)`<br>\newline
`x -= y` is equivalent to `x = x - y`.

<!-- void; operator-=; (matrix x, real y); -->
\index{{\tt \bfseries operator\_compound\_subtract}!{\tt (matrix x, real y): void}|hyperpage}

`void` **`operator-=`**`(matrix x, real y)`<br>\newline
`x -= y` is equivalent to `x = x - y`.

<!-- void; operator-=; (vector x, vector y); -->
\index{{\tt \bfseries operator\_compound\_subtract}!{\tt (vector x, vector y): void}|hyperpage}

`void` **`operator-=`**`(vector x, vector y)`<br>\newline
`x -= y` is equivalent to `x = x - y`.

<!-- void; operator-=; (row_vector x, row_vector y); -->
\index{{\tt \bfseries operator\_compound\_subtract}!{\tt (row\_vector x, row\_vector y): void}|hyperpage}

`void` **`operator-=`**`(row_vector x, row_vector y)`<br>\newline
`x -= y` is equivalent to `x = x - y`.

<!-- void; operator-=; (matrix x, matrix y); -->
\index{{\tt \bfseries operator\_compound\_subtract}!{\tt (matrix x, matrix y): void}|hyperpage}

`void` **`operator-=`**`(matrix x, matrix y)`<br>\newline
`x -= y` is equivalent to `x = x - y`.

## Compound Multiplication and Assignment

<!-- void; operator*=; (int x, int y); -->
\index{{\tt \bfseries operator\_compound\_multiply}!{\tt (int x, int y): void}|hyperpage}

`void` **`operator*=`**`(int x, int y)`<br>\newline
`x *= y` is equivalent to `x = x * y`.

<!-- void; operator*=; (real x, real y); -->
\index{{\tt \bfseries operator\_compound\_multiply}!{\tt (real x, real y): void}|hyperpage}

`void` **`operator*=`**`(real x, real y)`<br>\newline
`x *= y` is equivalent to `x = x * y`.

<!-- void; operator*=; (vector x, real y); -->
\index{{\tt \bfseries operator\_compound\_multiply}!{\tt (vector x, real y): void}|hyperpage}

`void` **`operator*=`**`(vector x, real y)`<br>\newline
`x *= y` is equivalent to `x = x * y`.

<!-- void; operator*=; (row_vector x, real y); -->
\index{{\tt \bfseries operator\_compound\_multiply}!{\tt (row\_vector x, real y): void}|hyperpage}

`void` **`operator*=`**`(row_vector x, real y)`<br>\newline
`x *= y` is equivalent to `x = x * y`.

<!-- void; operator*=; (matrix x, real y); -->
\index{{\tt \bfseries operator\_compound\_multiply}!{\tt (matrix x, real y): void}|hyperpage}

`void` **`operator*=`**`(matrix x, real y)`<br>\newline
`x *= y` is equivalent to `x = x * y`.

<!-- void; operator*=; (row_vector x, matrix y); -->
\index{{\tt \bfseries operator\_compound\_multiply}!{\tt (row\_vector x, matrix y): void}|hyperpage}

`void` **`operator*=`**`(row_vector x, matrix y)`<br>\newline
`x *= y` is equivalent to `x = x * y`.

<!-- void; operator*=; (matrix x, matrix y); -->
\index{{\tt \bfseries operator\_compound\_multiply}!{\tt (matrix x, matrix y): void}|hyperpage}

`void` **`operator*=`**`(matrix x, matrix y)`<br>\newline
`x *= y` is equivalent to `x = x * y`.

## Compound Division and Assignment

<!-- void; operator/=; (int x, int y); -->
\index{{\tt \bfseries operator\_compound\_divide}!{\tt (int x, int y): void}|hyperpage}

`void` **`operator/=`**`(int x, int y)`<br>\newline
`x /= y` is equivalent to `x = x / y`.

<!-- void; operator/=; (real x, real y); -->
\index{{\tt \bfseries operator\_compound\_divide}!{\tt (real x, real y): void}|hyperpage}

`void` **`operator/=`**`(real x, real y)`<br>\newline
`x /= y` is equivalent to `x = x / y`.

<!-- void; operator/=; (vector x, real y); -->
\index{{\tt \bfseries operator\_compound\_divide}!{\tt (vector x, real y): void}|hyperpage}

`void` **`operator/=`**`(vector x, real y)`<br>\newline
`x /= y` is equivalent to `x = x / y`.

<!-- void; operator/=; (row_vector x, real y); -->
\index{{\tt \bfseries operator\_compound\_divide}!{\tt (row\_vector x, real y): void}|hyperpage}

`void` **`operator/=`**`(row_vector x, real y)`<br>\newline
`x /= y` is equivalent to `x = x / y`.

<!-- void; operator/=; (matrix x, real y); -->
\index{{\tt \bfseries operator\_compound\_divide}!{\tt (matrix x, real y): void}|hyperpage}

`void` **`operator/=`**`(matrix x, real y)`<br>\newline
`x /= y` is equivalent to `x = x / y`.

## Compound Elementwise Multiplication and Assignment

<!-- void; operator.*=; (vector x, vector y); -->
\index{{\tt \bfseries operator\_compound\_elt\_multiply}!{\tt (vector x, vector y): void}|hyperpage}

`void` **`operator.*=`**`(vector x, vector y)`<br>\newline
`x .*= y` is equivalent to `x = x .* y`.

<!-- void; operator.*=; (row_vector x, row_vector y); -->
\index{{\tt \bfseries operator\_compound\_elt\_multiply}!{\tt (row\_vector x, row\_vector y): void}|hyperpage}

`void` **`operator.*=`**`(row_vector x, row_vector y)`<br>\newline
`x .*= y` is equivalent to `x = x .* y`.

<!-- void; operator.*=; (matrix x, matrix y); -->
\index{{\tt \bfseries operator\_compound\_elt\_multiply}!{\tt (matrix x, matrix y): void}|hyperpage}

`void` **`operator.*=`**`(matrix x, matrix y)`<br>\newline
`x .*= y` is equivalent to `x = x .* y`.

## Compound Elementwise Division and Assignment

<!-- void; operator./=; (vector x, vector y); -->
\index{{\tt \bfseries operator\_compound\_elt\_divide}!{\tt (vector x, vector y): void}|hyperpage}

`void` **`operator./=`**`(vector x, vector y)`<br>\newline
`x ./= y` is equivalent to `x = x ./ y`.

<!-- void; operator./=; (row_vector x, row_vector y); -->
\index{{\tt \bfseries operator\_compound\_elt\_divide}!{\tt (row\_vector x, row\_vector y): void}|hyperpage}

`void` **`operator./=`**`(row_vector x, row_vector y)`<br>\newline
`x ./= y` is equivalent to `x = x ./ y`.

<!-- void; operator./=; (matrix x, matrix y); -->
\index{{\tt \bfseries operator\_compound\_elt\_divide}!{\tt (matrix x, matrix y): void}|hyperpage}

`void` **`operator./=`**`(matrix x, matrix y)`<br>\newline
`x ./= y` is equivalent to `x = x ./ y`.

<!-- void; operator./=; (vector x, real y); -->
\index{{\tt \bfseries operator\_compound\_elt\_divide}!{\tt (vector x, real y): void}|hyperpage}

`void` **`operator./=`**`(vector x, real y)`<br>\newline
`x ./= y` is equivalent to `x = x ./ y`.

<!-- void; operator./=; (row_vector x, real y); -->
\index{{\tt \bfseries operator\_compound\_elt\_divide}!{\tt (row\_vector x, real y): void}|hyperpage}

`void` **`operator./=`**`(row_vector x, real y)`<br>\newline
`x ./= y` is equivalent to `x = x ./ y`.

<!-- void; operator./=; (matrix x, real y); -->
\index{{\tt \bfseries operator\_compound\_elt\_divide}!{\tt (matrix x, real y): void}|hyperpage}

`void` **`operator./=`**`(matrix x, real y)`<br>\newline
`x ./= y` is equivalent to `x = x ./ y`.

