# Positive Continuous Distributions

The positive continuous probability functions have support on the
positive real numbers.

```{r results='asis', echo=FALSE}
if (knitr::is_html_output()) {
cat(' * <a href="lognormal.html">Lognormal Distribution</a>\n')
cat(' * <a href="chi-square-distribution.html">Chi-Square Distribution</a>\n')
cat(' * <a href="inverse-chi-square-distribution.html">Inverse Chi-Square Distribution</a>\n')
cat(' * <a href="scaled-inverse-chi-square-distribution.html">Scaled Inverse Chi-Square Distribution</a>\n')
cat(' * <a href="exponential-distribution.html">Exponential Distribution</a>\n')
cat(' * <a href="gamma-distribution.html">Gamma Distribution</a>\n')
cat(' * <a href="inverse-gamma-distribution.html">Inverse Gamma Distribution</a>\n')
cat(' * <a href="weibull-distribution.html">Weibull Distribution</a>\n')
cat(' * <a href="frechet-distribution.html">Frechet Distribution</a>\n')
}
```

## Lognormal Distribution {#lognormal}

### Probability Density Function

If $\mu \in \mathbb{R}$ and $\sigma \in \mathbb{R}^+$, then for $y \in
\mathbb{R}^+$, \[ \text{LogNormal}(y|\mu,\sigma) = \frac{1}{\sqrt{2
\pi} \ \sigma} \, \frac{1}{y} \ \exp \! \left(        - \, \frac{1}{2}
\, \left( \frac{\log y - \mu}{\sigma} \right)^2      \right) . \]

### Sampling Statement

`y ~ ` **`lognormal`**`(mu, sigma)`

Increment target log probability density with `lognormal_lpdf( y | mu, sigma)`
dropping constant additive terms.
\index{{\tt \bfseries lognormal}!sampling statement|hyperpage}

### Stan Functions

<!-- real; lognormal_lpdf; (reals y | reals mu, reals sigma); -->
\index{{\tt \bfseries lognormal}!{\tt (reals y | reals mu, reals sigma): real}|hyperpage}

`real` **`lognormal_lpdf`**`(reals y | reals mu, reals sigma)`<br>\newline
The log of the lognormal density of y given location mu and scale
sigma

<!-- real; lognormal_cdf; (reals y, reals mu, reals sigma); -->
\index{{\tt \bfseries lognormal}!{\tt (reals y, reals mu, reals sigma): real}|hyperpage}

`real` **`lognormal_cdf`**`(reals y, reals mu, reals sigma)`<br>\newline
The cumulative lognormal distribution function of y given location mu
and scale sigma

<!-- real; lognormal_lcdf; (reals y | reals mu, reals sigma); -->
\index{{\tt \bfseries lognormal}!{\tt (reals y | reals mu, reals sigma): real}|hyperpage}

`real` **`lognormal_lcdf`**`(reals y | reals mu, reals sigma)`<br>\newline
The log of the lognormal cumulative distribution function of y given
location mu and scale sigma

<!-- real; lognormal_lccdf; (reals y | reals mu, reals sigma); -->
\index{{\tt \bfseries lognormal}!{\tt (reals y | reals mu, reals sigma): real}|hyperpage}

`real` **`lognormal_lccdf`**`(reals y | reals mu, reals sigma)`<br>\newline
The log of the lognormal complementary cumulative distribution
function of y given location mu and scale sigma

<!-- R; lognormal_rng; (reals mu, reals beta); -->
\index{{\tt \bfseries lognormal}!{\tt (reals mu, reals beta): R}|hyperpage}

`R` **`lognormal_rng`**`(reals mu, reals beta)`<br>\newline
Generate a lognormal variate with location mu and scale sigma; may
only be used in generated quantities block. For a description of
argument and return types, see section \@ref(prng-vectorization).

## Chi-Square Distribution

### Probability Density Function

If $\nu \in \mathbb{R}^+$, then for $y \in \mathbb{R}^+$, \[
\text{ChiSquare}(y|\nu) = \frac{2^{-\nu/2}}     {\Gamma(\nu / 2)} \,
y^{\nu/2 - 1} \, \exp \! \left( -\, \frac{1}{2} \, y \right) . \]

### Sampling Statement

`y ~ ` **`chi_square`**`(nu)`

Increment target log probability density with `chi_square_lpdf( y | nu)`
dropping constant additive terms.
\index{{\tt \bfseries chi\_square}!sampling statement|hyperpage}

### Stan Functions

<!-- real; chi_square_lpdf; (reals y | reals nu); -->
\index{{\tt \bfseries chi\_square}!{\tt (reals y | reals nu): real}|hyperpage}

`real` **`chi_square_lpdf`**`(reals y | reals nu)`<br>\newline
The log of the Chi-square density of y given degrees of freedom nu

<!-- real; chi_square_cdf; (reals y, reals nu); -->
\index{{\tt \bfseries chi\_square}!{\tt (reals y, reals nu): real}|hyperpage}

`real` **`chi_square_cdf`**`(reals y, reals nu)`<br>\newline
The Chi-square cumulative distribution function of y given degrees of
freedom nu

<!-- real; chi_square_lcdf; (reals y | reals nu); -->
\index{{\tt \bfseries chi\_square}!{\tt (reals y | reals nu): real}|hyperpage}

`real` **`chi_square_lcdf`**`(reals y | reals nu)`<br>\newline
The log of the Chi-square cumulative distribution function of y given
degrees of freedom nu

<!-- real; chi_square_lccdf; (reals y | reals nu); -->
\index{{\tt \bfseries chi\_square}!{\tt (reals y | reals nu): real}|hyperpage}

`real` **`chi_square_lccdf`**`(reals y | reals nu)`<br>\newline
The log of the complementary Chi-square cumulative distribution
function of y given degrees of freedom nu

<!-- R; chi_square_rng; (reals nu); -->
\index{{\tt \bfseries chi\_square}!{\tt (reals nu): R}|hyperpage}

`R` **`chi_square_rng`**`(reals nu)`<br>\newline
Generate a Chi-square variate with degrees of freedom nu; may only be
used in generated quantities block. For a description of argument and
return types, see section \@ref(prng-vectorization).

## Inverse Chi-Square Distribution

### Probability Density Function

If $\nu \in \mathbb{R}^+$, then for $y \in \mathbb{R}^+$, \[
\text{InvChiSquare}(y \, | \, \nu) = \frac{2^{-\nu/2}}    {\Gamma(\nu
/ 2)} \, y^{-\nu/2 - 1} \, \exp\! \left( \! - \, \frac{1}{2} \,
\frac{1}{y} \right) . \]

### Sampling Statement

`y ~ ` **`inv_chi_square`**`(nu)`

Increment target log probability density with `inv_chi_square_lpdf( y | nu)`
dropping constant additive terms.
\index{{\tt \bfseries inv\_chi\_square}!sampling statement|hyperpage}

### Stan Functions

<!-- real; inv_chi_square_lpdf; (reals y | reals nu); -->
\index{{\tt \bfseries inv\_chi\_square}!{\tt (reals y | reals nu): real}|hyperpage}

`real` **`inv_chi_square_lpdf`**`(reals y | reals nu)`<br>\newline
The log of the inverse Chi-square density of y given degrees of
freedom nu

<!-- real; inv_chi_square_cdf; (reals y, reals nu); -->
\index{{\tt \bfseries inv\_chi\_square}!{\tt (reals y, reals nu): real}|hyperpage}

`real` **`inv_chi_square_cdf`**`(reals y, reals nu)`<br>\newline
The inverse Chi-squared cumulative distribution function of y given
degrees of freedom nu

<!-- real; inv_chi_square_lcdf; (reals y | reals nu); -->
\index{{\tt \bfseries inv\_chi\_square}!{\tt (reals y | reals nu): real}|hyperpage}

`real` **`inv_chi_square_lcdf`**`(reals y | reals nu)`<br>\newline
The log of the inverse Chi-squared cumulative distribution function of
y given degrees of freedom nu

<!-- real; inv_chi_square_lccdf; (reals y | reals nu); -->
\index{{\tt \bfseries inv\_chi\_square}!{\tt (reals y | reals nu): real}|hyperpage}

`real` **`inv_chi_square_lccdf`**`(reals y | reals nu)`<br>\newline
The log of the inverse Chi-squared complementary cumulative
distribution function of y given degrees of freedom nu

<!-- R; inv_chi_square_rng; (reals nu); -->
\index{{\tt \bfseries inv\_chi\_square}!{\tt (reals nu): R}|hyperpage}

`R` **`inv_chi_square_rng`**`(reals nu)`<br>\newline
Generate an inverse Chi-squared variate with degrees of freedom nu;
may only be used in generated quantities block. For a description of
argument and return types, see section \@ref(prng-vectorization).

## Scaled Inverse Chi-Square Distribution

### Probability Density Function

If $\nu \in \mathbb{R}^+$ and $\sigma \in \mathbb{R}^+$, then for $y
\in \mathbb{R}^+$, \[ \text{ScaledInvChiSquare}(y|\nu,\sigma) =
\frac{(\nu / 2)^{\nu/2}}      {\Gamma(\nu / 2)} \, \sigma^{\nu} \,
y^{-(\nu/2 + 1)} \, \exp \! \left( \!    - \, \frac{1}{2} \, \nu \,
\sigma^2 \, \frac{1}{y} \right) . \]

### Sampling Statement

`y ~ ` **`scaled_inv_chi_square`**`(nu, sigma)`

Increment target log probability density with `scaled_inv_chi_square_lpdf( y | nu, sigma)`
dropping constant additive terms.
\index{{\tt \bfseries scaled\_inv\_chi\_square}!sampling statement|hyperpage}

### Stan Functions

<!-- real; scaled_inv_chi_square_lpdf; (reals y | reals nu, reals sigma); -->
\index{{\tt \bfseries scaled\_inv\_chi\_square}!{\tt (reals y | reals nu, reals sigma): real}|hyperpage}

`real` **`scaled_inv_chi_square_lpdf`**`(reals y | reals nu, reals sigma)`<br>\newline
The log of the scaled inverse Chi-square density of y given degrees of
freedom nu and scale sigma

<!-- real; scaled_inv_chi_square_cdf; (reals y, reals nu, reals sigma); -->
\index{{\tt \bfseries scaled\_inv\_chi\_square}!{\tt (reals y, reals nu, reals sigma): real}|hyperpage}

`real` **`scaled_inv_chi_square_cdf`**`(reals y, reals nu, reals sigma)`<br>\newline
The scaled inverse Chi-square cumulative distribution function of y
given degrees of freedom nu and scale sigma

<!-- real; scaled_inv_chi_square_lcdf; (reals y | reals nu, reals sigma); -->
\index{{\tt \bfseries scaled\_inv\_chi\_square}!{\tt (reals y | reals nu, reals sigma): real}|hyperpage}

`real` **`scaled_inv_chi_square_lcdf`**`(reals y | reals nu, reals sigma)`<br>\newline
The log of the scaled inverse Chi-square cumulative distribution
function of y given degrees of freedom nu and scale sigma

<!-- real; scaled_inv_chi_square_lccdf; (reals y | reals nu, reals sigma); -->
\index{{\tt \bfseries scaled\_inv\_chi\_square}!{\tt (reals y | reals nu, reals sigma): real}|hyperpage}

`real` **`scaled_inv_chi_square_lccdf`**`(reals y | reals nu, reals sigma)`<br>\newline
The log of the scaled inverse Chi-square complementary cumulative
distribution function of y given degrees of freedom nu and scale sigma

<!-- R; scaled_inv_chi_square_rng; (reals nu, reals sigma); -->
\index{{\tt \bfseries scaled\_inv\_chi\_square}!{\tt (reals nu, reals sigma): R}|hyperpage}

`R` **`scaled_inv_chi_square_rng`**`(reals nu, reals sigma)`<br>\newline
Generate a scaled inverse Chi-squared variate with degrees of freedom
nu and scale sigma; may only be used in generated quantities block.
For a description of argument and return types, see section
\@ref(prng-vectorization).

## Exponential Distribution {#exponential-distribution}

### Probability Density Function

If $\beta \in \mathbb{R}^+$, then for $y \in \mathbb{R}^+$, \[
\text{Exponential}(y|\beta) = \beta \, \exp ( - \beta \, y ) . \]

### Sampling Statement

`y ~ ` **`exponential`**`(beta)`

Increment target log probability density with `exponential_lpdf( y | beta)`
dropping constant additive terms.
\index{{\tt \bfseries exponential}!sampling statement|hyperpage}

### Stan Functions

<!-- real; exponential_lpdf; (reals y | reals beta); -->
\index{{\tt \bfseries exponential}!{\tt (reals y | reals beta): real}|hyperpage}

`real` **`exponential_lpdf`**`(reals y | reals beta)`<br>\newline
The log of the exponential density of y given inverse scale beta

<!-- real; exponential_cdf; (reals y, reals beta); -->
\index{{\tt \bfseries exponential}!{\tt (reals y, reals beta): real}|hyperpage}

`real` **`exponential_cdf`**`(reals y, reals beta)`<br>\newline
The exponential cumulative distribution function of y given inverse
scale beta

<!-- real; exponential_lcdf; (reals y | reals beta); -->
\index{{\tt \bfseries exponential}!{\tt (reals y | reals beta): real}|hyperpage}

`real` **`exponential_lcdf`**`(reals y | reals beta)`<br>\newline
The log of the exponential cumulative distribution function of y given
inverse scale beta

<!-- real; exponential_lccdf; (reals y | reals beta); -->
\index{{\tt \bfseries exponential}!{\tt (reals y | reals beta): real}|hyperpage}

`real` **`exponential_lccdf`**`(reals y | reals beta)`<br>\newline
The log of the exponential complementary cumulative distribution
function of y given inverse scale beta

<!-- R; exponential_rng; (reals beta); -->
\index{{\tt \bfseries exponential}!{\tt (reals beta): R}|hyperpage}

`R` **`exponential_rng`**`(reals beta)`<br>\newline
Generate an exponential variate with inverse scale beta; may only be
used in generated quantities block. For a description of argument and
return types, see section \@ref(prng-vectorization).

## Gamma Distribution

### Probability Density Function

If $\alpha \in \mathbb{R}^+$ and $\beta \in \mathbb{R}^+$, then for $y
\in \mathbb{R}^+$, \[ \text{Gamma}(y|\alpha,\beta) =
\frac{\beta^{\alpha}}      {\Gamma(\alpha)} \, y^{\alpha - 1}
\exp(-\beta \, y) . \]

### Sampling Statement

`y ~ ` **`gamma`**`(alpha, beta)`

Increment target log probability density with `gamma_lpdf( y | alpha, beta)`
dropping constant additive terms.
\index{{\tt \bfseries gamma}!sampling statement|hyperpage}

### Stan Functions

<!-- real; gamma_lpdf; (reals y | reals alpha, reals beta); -->
\index{{\tt \bfseries gamma}!{\tt (reals y | reals alpha, reals beta): real}|hyperpage}

`real` **`gamma_lpdf`**`(reals y | reals alpha, reals beta)`<br>\newline
The log of the gamma density of y given shape alpha and inverse scale
beta

<!-- real; gamma_cdf; (reals y, reals alpha, reals beta); -->
\index{{\tt \bfseries gamma}!{\tt (reals y, reals alpha, reals beta): real}|hyperpage}

`real` **`gamma_cdf`**`(reals y, reals alpha, reals beta)`<br>\newline
The cumulative gamma distribution function of y given shape alpha and
inverse scale beta

<!-- real; gamma_lcdf; (reals y | reals alpha, reals beta); -->
\index{{\tt \bfseries gamma}!{\tt (reals y | reals alpha, reals beta): real}|hyperpage}

`real` **`gamma_lcdf`**`(reals y | reals alpha, reals beta)`<br>\newline
The log of the cumulative gamma distribution function of y given shape
alpha and inverse scale beta

<!-- real; gamma_lccdf; (reals y | reals alpha, reals beta); -->
\index{{\tt \bfseries gamma}!{\tt (reals y | reals alpha, reals beta): real}|hyperpage}

`real` **`gamma_lccdf`**`(reals y | reals alpha, reals beta)`<br>\newline
The log of the complementary cumulative gamma distribution function of
y given shape alpha and inverse scale beta

<!-- R; gamma_rng; (reals alpha, reals beta); -->
\index{{\tt \bfseries gamma}!{\tt (reals alpha, reals beta): R}|hyperpage}

`R` **`gamma_rng`**`(reals alpha, reals beta)`<br>\newline
Generate a gamma variate with shape alpha and inverse scale beta; may
only be used in generated quantities block. For a description of
argument and return types, see section \@ref(prng-vectorization).

## Inverse Gamma Distribution

### Probability Density Function

If $\alpha \in \mathbb{R}^+$ and $\beta \in \mathbb{R}^+$, then for $y
\in \mathbb{R}^+$, \[ \text{InvGamma}(y|\alpha,\beta) =
\frac{\beta^{\alpha}}      {\Gamma(\alpha)} \ y^{-(\alpha + 1)} \,
\exp \! \left( \! - \beta \, \frac{1}{y} \right) . \]

### Sampling Statement

`y ~ ` **`inv_gamma`**`(alpha, beta)`

Increment target log probability density with `inv_gamma_lpdf( y | alpha, beta)`
dropping constant additive terms.
\index{{\tt \bfseries inv\_gamma}!sampling statement|hyperpage}

### Stan Functions

<!-- real; inv_gamma_lpdf; (reals y | reals alpha, reals beta); -->
\index{{\tt \bfseries inv\_gamma}!{\tt (reals y | reals alpha, reals beta): real}|hyperpage}

`real` **`inv_gamma_lpdf`**`(reals y | reals alpha, reals beta)`<br>\newline
The log of the inverse gamma density of y given shape alpha and scale
beta

<!-- real; inv_gamma_cdf; (reals y, reals alpha, reals beta); -->
\index{{\tt \bfseries inv\_gamma}!{\tt (reals y, reals alpha, reals beta): real}|hyperpage}

`real` **`inv_gamma_cdf`**`(reals y, reals alpha, reals beta)`<br>\newline
The inverse gamma cumulative distribution function of y given shape
alpha and scale beta

<!-- real; inv_gamma_lcdf; (reals y | reals alpha, reals beta); -->
\index{{\tt \bfseries inv\_gamma}!{\tt (reals y | reals alpha, reals beta): real}|hyperpage}

`real` **`inv_gamma_lcdf`**`(reals y | reals alpha, reals beta)`<br>\newline
The log of the inverse gamma cumulative distribution function of y
given shape alpha and scale beta

<!-- real; inv_gamma_lccdf; (reals y | reals alpha, reals beta); -->
\index{{\tt \bfseries inv\_gamma}!{\tt (reals y | reals alpha, reals beta): real}|hyperpage}

`real` **`inv_gamma_lccdf`**`(reals y | reals alpha, reals beta)`<br>\newline
The log of the inverse gamma complementary cumulative distribution
function of y given shape alpha and scale beta

<!-- R; inv_gamma_rng; (reals alpha, reals beta); -->
\index{{\tt \bfseries inv\_gamma}!{\tt (reals alpha, reals beta): R}|hyperpage}

`R` **`inv_gamma_rng`**`(reals alpha, reals beta)`<br>\newline
Generate an inverse gamma variate with shape alpha and scale beta; may
only be used in generated quantities block. For a description of
argument and return types, see section \@ref(prng-vectorization).

## Weibull Distribution

### Probability Density Function

If $\alpha \in \mathbb{R}^+$ and $\sigma \in \mathbb{R}^+$, then for
$y \in [0,\infty)$, \[ \text{Weibull}(y|\alpha,\sigma) =
\frac{\alpha}{\sigma} \, \left( \frac{y}{\sigma} \right)^{\alpha - 1}
\, \exp \! \left( \! - \left( \frac{y}{\sigma} \right)^{\alpha}
\right) . \]

Note that if $Y \propto \text{Weibull}(\alpha,\sigma)$, then $Y^{-1}
\propto \text{Frechet}(\alpha,\sigma^{-1})$.

### Sampling Statement

`y ~ ` **`weibull`**`(alpha, sigma)`

Increment target log probability density with `weibull_lpdf( y | alpha, sigma)`
dropping constant additive terms.
\index{{\tt \bfseries weibull}!sampling statement|hyperpage}

### Stan Functions

<!-- real; weibull_lpdf; (reals y | reals alpha, reals sigma); -->
\index{{\tt \bfseries weibull}!{\tt (reals y | reals alpha, reals sigma): real}|hyperpage}

`real` **`weibull_lpdf`**`(reals y | reals alpha, reals sigma)`<br>\newline
The log of the Weibull density of y given shape alpha and scale sigma

<!-- real; weibull_cdf; (reals y, reals alpha, reals sigma); -->
\index{{\tt \bfseries weibull}!{\tt (reals y, reals alpha, reals sigma): real}|hyperpage}

`real` **`weibull_cdf`**`(reals y, reals alpha, reals sigma)`<br>\newline
The Weibull cumulative distribution function of y given shape alpha
and scale sigma

<!-- real; weibull_lcdf; (reals y | reals alpha, reals sigma); -->
\index{{\tt \bfseries weibull}!{\tt (reals y | reals alpha, reals sigma): real}|hyperpage}

`real` **`weibull_lcdf`**`(reals y | reals alpha, reals sigma)`<br>\newline
The log of the Weibull cumulative distribution function of y given
shape alpha and scale sigma

<!-- real; weibull_lccdf; (reals y | reals alpha, reals sigma); -->
\index{{\tt \bfseries weibull}!{\tt (reals y | reals alpha, reals sigma): real}|hyperpage}

`real` **`weibull_lccdf`**`(reals y | reals alpha, reals sigma)`<br>\newline
The log of the Weibull complementary cumulative distribution function
of y given shape alpha and scale sigma

<!-- R; weibull_rng; (reals alpha, reals sigma); -->
\index{{\tt \bfseries weibull}!{\tt (reals alpha, reals sigma): R}|hyperpage}

`R` **`weibull_rng`**`(reals alpha, reals sigma)`<br>\newline
Generate a weibull variate with shape alpha and scale sigma; may only
be used in generated quantities block. For a description of argument
and return types, see section \@ref(prng-vectorization).

## Frechet Distribution

### Probability Density Function

If $\alpha \in \mathbb{R}^+$ and $\sigma \in \mathbb{R}^+$, then for
$y \in \mathbb{R}^+$, \[ \text{Frechet}(y|\alpha,\sigma) =
\frac{\alpha}{\sigma} \, \left( \frac{y}{\sigma} \right)^{-\alpha - 1}
\, \exp \! \left( \! - \left( \frac{y}{\sigma} \right)^{-\alpha}
\right) . \]

Note that if $Y \propto \text{Frechet}(\alpha,\sigma)$, then $Y^{-1}
\propto \text{Weibull}(\alpha,\sigma^{-1})$.

### Sampling Statement

`y ~ ` **`frechet`**`(alpha, sigma)`

Increment target log probability density with `frechet_lpdf( y | alpha, sigma)`
dropping constant additive terms.
\index{{\tt \bfseries frechet}!sampling statement|hyperpage}

### Stan Functions

<!-- real; frechet_lpdf; (reals y | reals alpha, reals sigma); -->
\index{{\tt \bfseries frechet}!{\tt (reals y | reals alpha, reals sigma): real}|hyperpage}

`real` **`frechet_lpdf`**`(reals y | reals alpha, reals sigma)`<br>\newline
The log of the Frechet density of y given shape alpha and scale sigma

<!-- real; frechet_cdf; (reals y, reals alpha, reals sigma); -->
\index{{\tt \bfseries frechet}!{\tt (reals y, reals alpha, reals sigma): real}|hyperpage}

`real` **`frechet_cdf`**`(reals y, reals alpha, reals sigma)`<br>\newline
The Frechet cumulative distribution function of y given shape alpha
and scale sigma

<!-- real; frechet_lcdf; (reals y | reals alpha, reals sigma); -->
\index{{\tt \bfseries frechet}!{\tt (reals y | reals alpha, reals sigma): real}|hyperpage}

`real` **`frechet_lcdf`**`(reals y | reals alpha, reals sigma)`<br>\newline
The log of the Frechet cumulative distribution function of y given
shape alpha and scale sigma

<!-- real; frechet_lccdf; (reals y | reals alpha, reals sigma); -->
\index{{\tt \bfseries frechet}!{\tt (reals y | reals alpha, reals sigma): real}|hyperpage}

`real` **`frechet_lccdf`**`(reals y | reals alpha, reals sigma)`<br>\newline
The log of the Frechet complementary cumulative distribution function
of y given shape alpha and scale sigma

<!-- R; frechet_rng; (reals alpha, reals sigma); -->
\index{{\tt \bfseries frechet}!{\tt (reals alpha, reals sigma): R}|hyperpage}

`R` **`frechet_rng`**`(reals alpha, reals sigma)`<br>\newline
Generate an Frechet variate with shape alpha and scale sigma; may only
be used in generated quantities block. For a description of argument
and return types, see section \@ref(prng-vectorization).

