#ifndef __STAN__DIFF__VAR_HPP__
#define __STAN__DIFF__VAR_HPP__

#include <stan/diff/rev/var_stack.hpp>
#include <stan/diff/rev/chainable.hpp>
#include <stan/diff/rev/vari.hpp>
#include <stan/diff/rev/var.hpp>
#include <stan/diff/rev/print_stack.hpp>
#include <stan/diff/rev/boost_fpclassify.hpp>
#include <stan/diff/rev/traits.hpp>

#include <stan/diff/rev/op/v_vari.hpp>
#include <stan/diff/rev/op/vv_vari.hpp>
#include <stan/diff/rev/op/vd_vari.hpp>
#include <stan/diff/rev/op/dv_vari.hpp>
#include <stan/diff/rev/op/vvv_vari.hpp>
#include <stan/diff/rev/op/vvd_vari.hpp>
#include <stan/diff/rev/op/vdv_vari.hpp>
#include <stan/diff/rev/op/vdd_vari.hpp>
#include <stan/diff/rev/op/dvv_vari.hpp>
#include <stan/diff/rev/op/dvd_vari.hpp>
#include <stan/diff/rev/op/ddv_vari.hpp>
#include <stan/diff/rev/precomp_v_vari.hpp>

#include <stan/diff/rev/operator_unary_negative.hpp>
#include <stan/diff/rev/operator_equal.hpp>
#include <stan/diff/rev/operator_not_equal.hpp>
#include <stan/diff/rev/operator_greater_than.hpp>
#include <stan/diff/rev/operator_greater_than_or_equal.hpp>
#include <stan/diff/rev/operator_less_than.hpp>
#include <stan/diff/rev/operator_less_than_or_equal.hpp>
#include <stan/diff/rev/operator_unary_not.hpp>
#include <stan/diff/rev/operator_unary_plus.hpp>
#include <stan/diff/rev/operator_addition.hpp>
#include <stan/diff/rev/operator_subtraction.hpp>
#include <stan/diff/rev/operator_multiplication.hpp>
#include <stan/diff/rev/operator_division.hpp>
#include <stan/diff/rev/operator_unary_increment.hpp>
#include <stan/diff/rev/operator_unary_decrement.hpp>

#include <stan/diff/rev/exp.hpp>
#include <stan/diff/rev/log.hpp>
#include <stan/diff/rev/log10.hpp>
#include <stan/diff/rev/sqrt.hpp>
#include <stan/diff/rev/pow.hpp>
#include <stan/diff/rev/inv.hpp>
#include <stan/diff/rev/inv_sqrt.hpp>
#include <stan/diff/rev/inv_square.hpp>
#include <stan/diff/rev/cos.hpp>
#include <stan/diff/rev/sin.hpp>
#include <stan/diff/rev/tan.hpp>
#include <stan/diff/rev/acos.hpp>
#include <stan/diff/rev/asin.hpp>
#include <stan/diff/rev/atan.hpp>
#include <stan/diff/rev/atan2.hpp>
#include <stan/diff/rev/cosh.hpp>
#include <stan/diff/rev/sinh.hpp>
#include <stan/diff/rev/tanh.hpp>
#include <stan/diff/rev/fabs.hpp>
#include <stan/diff/rev/floor.hpp>
#include <stan/diff/rev/ceil.hpp>
#include <stan/diff/rev/fmod.hpp>
#include <stan/diff/rev/abs.hpp>
#include <stan/diff/rev/jacobian.hpp>

#include <stan/diff/rev/operator_plus_equal.hpp>
#include <stan/diff/rev/operator_minus_equal.hpp>
#include <stan/diff/rev/operator_multiply_equal.hpp>
#include <stan/diff/rev/operator_divide_equal.hpp>

#include <stan/diff/rev/numeric_limits.hpp>
#include <stan/diff/rev/is_uninitialized.hpp>

#include <stan/diff/rev/acosh.hpp>
#include <stan/diff/rev/atanh.hpp>
#include <stan/diff/rev/asinh.hpp>
#include <stan/diff/rev/erf.hpp>
#include <stan/diff/rev/erfc.hpp>
#include <stan/diff/rev/exp2.hpp>
#include <stan/diff/rev/expm1.hpp>
#include <stan/diff/rev/lgamma.hpp>
#include <stan/diff/rev/log1p.hpp>
#include <stan/diff/rev/log1m.hpp>
#include <stan/diff/rev/fma.hpp>
#include <stan/diff/rev/fmax.hpp>
#include <stan/diff/rev/fmin.hpp>
#include <stan/diff/rev/gamma_p.hpp>
#include <stan/diff/rev/gamma_q.hpp>
#include <stan/diff/rev/hypot.hpp>
#include <stan/diff/rev/log2.hpp>
#include <stan/diff/rev/cbrt.hpp>
#include <stan/diff/rev/round.hpp>
#include <stan/diff/rev/trunc.hpp>
#include <stan/diff/rev/fdim.hpp>
#include <stan/diff/rev/tgamma.hpp>
#include <stan/diff/rev/step.hpp>
#include <stan/diff/rev/inv_cloglog.hpp>
#include <stan/diff/rev/Phi.hpp>
#include <stan/diff/rev/inv_logit.hpp>
#include <stan/diff/rev/Phi_approx.hpp>
#include <stan/diff/rev/log_loss.hpp>
#include <stan/diff/rev/log1m_exp.hpp>
#include <stan/diff/rev/log1p_exp.hpp>
#include <stan/diff/rev/log_diff_exp.hpp>
#include <stan/diff/rev/log_sum_exp.hpp>
#include <stan/diff/rev/square.hpp>
#include <stan/diff/rev/multiply_log.hpp>
#include <stan/diff/rev/if_else.hpp>
#include <stan/diff/rev/ibeta.hpp>
#include <stan/diff/rev/value_of.hpp>
#include <stan/diff/rev/as_bool.hpp>
#include <stan/diff/rev/owens_t.hpp>
#include <stan/diff/rev/bessel_first_kind.hpp>
#include <stan/diff/rev/bessel_second_kind.hpp>
#include <stan/diff/rev/modified_bessel_first_kind.hpp>
#include <stan/diff/rev/modified_bessel_second_kind.hpp>
#include <stan/diff/rev/falling_factorial.hpp>
#include <stan/diff/rev/rising_factorial.hpp>
#include <stan/diff/rev/log_falling_factorial.hpp>
#include <stan/diff/rev/log_rising_factorial.hpp>

#include <stan/diff/rev/error_handling/matrix/check_pos_definite.hpp>

#endif
