#ifndef __STAN__PROB__DISTRIBUTIONS__MULTIVARIATE__DISCRETE_HPP__
#define __STAN__PROB__DISTRIBUTIONS__MULTIVARIATE__DISCRETE_HPP__

#include <stan/prob/distributions/univariate/discrete/categorical.hpp>

#endif
