test_paridx_fun <- function() {
  names <- c("alpha", "beta.1", "beta.2", "lp__", "treedepth__", "stepsize__") 
  paridx <- rstan:::paridx_fun(names)
  meta <- 4:6; names(meta) <- c("lp__", "treedepth__", "stepsize__")
  exp <- c(1, 2, 3); attr(exp, 'meta') <- meta
  checkEquals(paridx, exp)
  paridx2 <- rstan:::paridx_fun(names[-5])
  meta <- 4:5; names(meta) <- c("lp__", "stepsize__")
  attr(exp, 'meta') <- meta
  checkEquals(paridx2, exp)
  paridx3 <- rstan:::paridx_fun(names[-(4:6)])
  meta <- integer(0); names(meta) <- character(0)
  attr(exp, 'meta') <- meta 
  checkEquals(paridx3, exp)
}

test_parse_stancsv_comments3 <- function() {
  comments <- c("# Samples Generated by Stan", 
                "#", 
                "# stan_version_major=1", 
                "# stan_version_minor=2", 
                "# stan_version_patch=0", 
                "# data=dogs.data.R", 
                "# init=random initialization", 
                "# append_samples=0", 
                "# save_warmup=0", 
                "# seed=1340384924", 
                "# chain_id=4", 
                "# iter=2000", 
                "# warmup=1000", 
                "# thin=1", 
                "# nondiag_mass=1", 
                "# equal_step_sizes=0", 
                "# leapfrog_steps=-1", 
                "# max_treedepth=10", 
                "# epsilon=-1", 
                "# epsilon_pm=0", 
                "# delta=0.5", 
                "# gamma=0.05", 
                "#", 
                "# (mcmc::nuts_nondiag) adaptation finished", 
                "# step size=0.209005", 
                "# estimated covariance matrix:", 
                "#0.623755,-0.485771,", 
                "#-0.485771,1.37624,") 
  lst <- rstan:::parse_stancsv_comments(comments)
  checkEquals(lst$nondiag_mass, 1)
}

test_parse_stancsv_comments2 <- function() {
  comments <- c("# Samples Generated by Stan", 
                "# stan_version_major=1", 
                "# stan_version_minor=0", 
                "# stan_version_patch=2", 
                "# init=random",
                "# append_samples=0",
                "# seed=4294967295",
                "# chain_id=1",
                "# chain_id_src=user",
                "# iter=2000",
                "# warmup=1000",
                "# thin=1",
                "# nondiag_mass=0",
                "# leapfrog_steps=-1",
                "# max_treedepth=10",
                "# epsilon=-1",
                "# save_warmup=1",
                "# equal_step_sizes=0",
                "# epsilon_pm=0",
                "# delta=0.5",
                "# gamma=0.05",
                "#",
                "# (mcmc::nuts_nondiag) adaptation finished",
                "# step size=3.46559",
                "# parameter step size multipliers:",
                "# 0.732238,1.25278,1.0207,1.11686,0.947377,0.966707,0.975009,1.03381,1.32098,0.0933892) ")
  lst <- rstan:::parse_stancsv_comments(comments)
  existence <- c("seed", "chain_id", "iter", "warmup", "thin", "leapfrog_steps", "nondiag_mass",
                 "max_treedepth", "save_warmup", "epsilon_pm", "epsilon",
                 "delta", "gamma", "adaptation_info") %in% names(lst)
  checkTrue(all(existence))
  checkEquals(lst$seed, "4294967295")
  checkEquals(lst$epsilon, -1)
  checkEquals(lst$delta, .5)
}

test_parse_stancsv_comments <- function() {
  comments <- c("# Samples Generated by Stan", 
                "# stan_version_major=1", 
                "# stan_version_minor=0", 
                "# stan_version_patch=2", 
                "# init=random",
                "# append_samples=0",
                "# seed=4294967295",
                "# chain_id=1",
                "# chain_id_src=user",
                "# iter=2000",
                "# warmup=1000",
                "# thin=1",
                "# leapfrog_steps=-1",
                "# max_treedepth=10",
                "# epsilon=-1",
                "# save_warmup=1",
                "# equal_step_sizes=0",
                "# epsilon_pm=0",
                "# delta=0.5",
                "# gamma=0.05",
                "#",
                "# (mcmc::nuts_diag) adaptation finished",
                "# step size=3.46559",
                "# parameter step size multipliers:",
                "# 0.732238,1.25278,1.0207,1.11686,0.947377,0.966707,0.975009,1.03381,1.32098,0.0933892) ")
  lst <- rstan:::parse_stancsv_comments(comments)
  existence <- c("seed", "chain_id", "iter", "warmup", "thin", "leapfrog_steps",
                 "max_treedepth", "save_warmup", "epsilon_pm", "epsilon",
                 "delta", "gamma", "adaptation_info") %in% names(lst)
  checkTrue(all(existence))
  checkEquals(lst$seed, "4294967295")
  checkEquals(lst$epsilon, -1)
  checkEquals(lst$delta, .5)
}
