data { 
  int d_int;
  int d_int_array[d_int];
  real d_real;
  real d_real_array[d_int];
  vector[d_int] d_vector;
  row_vector[d_int] d_row_vector;
}
transformed data {
  real transformed_data_real;

  transformed_data_real <- neg_binomial_2_log(d_int, d_int, d_int);
  transformed_data_real <- neg_binomial_2_log(d_int, d_int, d_real);
  transformed_data_real <- neg_binomial_2_log(d_int, d_int, d_real_array);
  transformed_data_real <- neg_binomial_2_log(d_int, d_int, d_vector);
  transformed_data_real <- neg_binomial_2_log(d_int, d_int, d_row_vector);
  transformed_data_real <- neg_binomial_2_log(d_int, d_real, d_int);
  transformed_data_real <- neg_binomial_2_log(d_int, d_real, d_real);
  transformed_data_real <- neg_binomial_2_log(d_int, d_real, d_real_array);
  transformed_data_real <- neg_binomial_2_log(d_int, d_real, d_vector);
  transformed_data_real <- neg_binomial_2_log(d_int, d_real, d_row_vector);
  transformed_data_real <- neg_binomial_2_log(d_int, d_real_array, d_int);
  transformed_data_real <- neg_binomial_2_log(d_int, d_real_array, d_real);
  transformed_data_real <- neg_binomial_2_log(d_int, d_real_array, d_real_array);
  transformed_data_real <- neg_binomial_2_log(d_int, d_real_array, d_vector);
  transformed_data_real <- neg_binomial_2_log(d_int, d_real_array, d_row_vector);
  transformed_data_real <- neg_binomial_2_log(d_int, d_vector, d_int);
  transformed_data_real <- neg_binomial_2_log(d_int, d_vector, d_real);
  transformed_data_real <- neg_binomial_2_log(d_int, d_vector, d_real_array);
  transformed_data_real <- neg_binomial_2_log(d_int, d_vector, d_vector);
  transformed_data_real <- neg_binomial_2_log(d_int, d_vector, d_row_vector);
  transformed_data_real <- neg_binomial_2_log(d_int, d_row_vector, d_int);
  transformed_data_real <- neg_binomial_2_log(d_int, d_row_vector, d_real);
  transformed_data_real <- neg_binomial_2_log(d_int, d_row_vector, d_real_array);
  transformed_data_real <- neg_binomial_2_log(d_int, d_row_vector, d_vector);
  transformed_data_real <- neg_binomial_2_log(d_int, d_row_vector, d_row_vector);
  transformed_data_real <- neg_binomial_2_log(d_int_array, d_int, d_int);
  transformed_data_real <- neg_binomial_2_log(d_int_array, d_int, d_real);
  transformed_data_real <- neg_binomial_2_log(d_int_array, d_int, d_real_array);
  transformed_data_real <- neg_binomial_2_log(d_int_array, d_int, d_vector);
  transformed_data_real <- neg_binomial_2_log(d_int_array, d_int, d_row_vector);
  transformed_data_real <- neg_binomial_2_log(d_int_array, d_real, d_int);
  transformed_data_real <- neg_binomial_2_log(d_int_array, d_real, d_real);
  transformed_data_real <- neg_binomial_2_log(d_int_array, d_real, d_real_array);
  transformed_data_real <- neg_binomial_2_log(d_int_array, d_real, d_vector);
  transformed_data_real <- neg_binomial_2_log(d_int_array, d_real, d_row_vector);
  transformed_data_real <- neg_binomial_2_log(d_int_array, d_real_array, d_int);
  transformed_data_real <- neg_binomial_2_log(d_int_array, d_real_array, d_real);
  transformed_data_real <- neg_binomial_2_log(d_int_array, d_real_array, d_real_array);
  transformed_data_real <- neg_binomial_2_log(d_int_array, d_real_array, d_vector);
  transformed_data_real <- neg_binomial_2_log(d_int_array, d_real_array, d_row_vector);
  transformed_data_real <- neg_binomial_2_log(d_int_array, d_vector, d_int);
  transformed_data_real <- neg_binomial_2_log(d_int_array, d_vector, d_real);
  transformed_data_real <- neg_binomial_2_log(d_int_array, d_vector, d_real_array);
  transformed_data_real <- neg_binomial_2_log(d_int_array, d_vector, d_vector);
  transformed_data_real <- neg_binomial_2_log(d_int_array, d_vector, d_row_vector);
  transformed_data_real <- neg_binomial_2_log(d_int_array, d_row_vector, d_int);
  transformed_data_real <- neg_binomial_2_log(d_int_array, d_row_vector, d_real);
  transformed_data_real <- neg_binomial_2_log(d_int_array, d_row_vector, d_real_array);
  transformed_data_real <- neg_binomial_2_log(d_int_array, d_row_vector, d_vector);
  transformed_data_real <- neg_binomial_2_log(d_int_array, d_row_vector, d_row_vector);
}
parameters {
  real p_real;
  real p_real_array[d_int];
  vector[d_int] p_vector;
  row_vector[d_int] p_row_vector;

  real y_p;
}
transformed parameters {
  real transformed_param_real;

  transformed_param_real <- neg_binomial_2_log(d_int, d_int, d_int);
  transformed_param_real <- neg_binomial_2_log(d_int, d_int, d_real);
  transformed_param_real <- neg_binomial_2_log(d_int, d_int, d_real_array);
  transformed_param_real <- neg_binomial_2_log(d_int, d_int, d_vector);
  transformed_param_real <- neg_binomial_2_log(d_int, d_int, d_row_vector);
  transformed_param_real <- neg_binomial_2_log(d_int, d_int, p_real);
  transformed_param_real <- neg_binomial_2_log(d_int, d_int, p_real_array);
  transformed_param_real <- neg_binomial_2_log(d_int, d_int, p_vector);
  transformed_param_real <- neg_binomial_2_log(d_int, d_int, p_row_vector);
  transformed_param_real <- neg_binomial_2_log(d_int, d_real, d_int);
  transformed_param_real <- neg_binomial_2_log(d_int, d_real, d_real);
  transformed_param_real <- neg_binomial_2_log(d_int, d_real, d_real_array);
  transformed_param_real <- neg_binomial_2_log(d_int, d_real, d_vector);
  transformed_param_real <- neg_binomial_2_log(d_int, d_real, d_row_vector);
  transformed_param_real <- neg_binomial_2_log(d_int, d_real, p_real);
  transformed_param_real <- neg_binomial_2_log(d_int, d_real, p_real_array);
  transformed_param_real <- neg_binomial_2_log(d_int, d_real, p_vector);
  transformed_param_real <- neg_binomial_2_log(d_int, d_real, p_row_vector);
  transformed_param_real <- neg_binomial_2_log(d_int, d_real_array, d_int);
  transformed_param_real <- neg_binomial_2_log(d_int, d_real_array, d_real);
  transformed_param_real <- neg_binomial_2_log(d_int, d_real_array, d_real_array);
  transformed_param_real <- neg_binomial_2_log(d_int, d_real_array, d_vector);
  transformed_param_real <- neg_binomial_2_log(d_int, d_real_array, d_row_vector);
  transformed_param_real <- neg_binomial_2_log(d_int, d_real_array, p_real);
  transformed_param_real <- neg_binomial_2_log(d_int, d_real_array, p_real_array);
  transformed_param_real <- neg_binomial_2_log(d_int, d_real_array, p_vector);
  transformed_param_real <- neg_binomial_2_log(d_int, d_real_array, p_row_vector);
  transformed_param_real <- neg_binomial_2_log(d_int, d_vector, d_int);
  transformed_param_real <- neg_binomial_2_log(d_int, d_vector, d_real);
  transformed_param_real <- neg_binomial_2_log(d_int, d_vector, d_real_array);
  transformed_param_real <- neg_binomial_2_log(d_int, d_vector, d_vector);
  transformed_param_real <- neg_binomial_2_log(d_int, d_vector, d_row_vector);
  transformed_param_real <- neg_binomial_2_log(d_int, d_vector, p_real);
  transformed_param_real <- neg_binomial_2_log(d_int, d_vector, p_real_array);
  transformed_param_real <- neg_binomial_2_log(d_int, d_vector, p_vector);
  transformed_param_real <- neg_binomial_2_log(d_int, d_vector, p_row_vector);
  transformed_param_real <- neg_binomial_2_log(d_int, d_row_vector, d_int);
  transformed_param_real <- neg_binomial_2_log(d_int, d_row_vector, d_real);
  transformed_param_real <- neg_binomial_2_log(d_int, d_row_vector, d_real_array);
  transformed_param_real <- neg_binomial_2_log(d_int, d_row_vector, d_vector);
  transformed_param_real <- neg_binomial_2_log(d_int, d_row_vector, d_row_vector);
  transformed_param_real <- neg_binomial_2_log(d_int, d_row_vector, p_real);
  transformed_param_real <- neg_binomial_2_log(d_int, d_row_vector, p_real_array);
  transformed_param_real <- neg_binomial_2_log(d_int, d_row_vector, p_vector);
  transformed_param_real <- neg_binomial_2_log(d_int, d_row_vector, p_row_vector);
  transformed_param_real <- neg_binomial_2_log(d_int, p_real, d_int);
  transformed_param_real <- neg_binomial_2_log(d_int, p_real, d_real);
  transformed_param_real <- neg_binomial_2_log(d_int, p_real, d_real_array);
  transformed_param_real <- neg_binomial_2_log(d_int, p_real, d_vector);
  transformed_param_real <- neg_binomial_2_log(d_int, p_real, d_row_vector);
  transformed_param_real <- neg_binomial_2_log(d_int, p_real, p_real);
  transformed_param_real <- neg_binomial_2_log(d_int, p_real, p_real_array);
  transformed_param_real <- neg_binomial_2_log(d_int, p_real, p_vector);
  transformed_param_real <- neg_binomial_2_log(d_int, p_real, p_row_vector);
  transformed_param_real <- neg_binomial_2_log(d_int, p_real_array, d_int);
  transformed_param_real <- neg_binomial_2_log(d_int, p_real_array, d_real);
  transformed_param_real <- neg_binomial_2_log(d_int, p_real_array, d_real_array);
  transformed_param_real <- neg_binomial_2_log(d_int, p_real_array, d_vector);
  transformed_param_real <- neg_binomial_2_log(d_int, p_real_array, d_row_vector);
  transformed_param_real <- neg_binomial_2_log(d_int, p_real_array, p_real);
  transformed_param_real <- neg_binomial_2_log(d_int, p_real_array, p_real_array);
  transformed_param_real <- neg_binomial_2_log(d_int, p_real_array, p_vector);
  transformed_param_real <- neg_binomial_2_log(d_int, p_real_array, p_row_vector);
  transformed_param_real <- neg_binomial_2_log(d_int, p_vector, d_int);
  transformed_param_real <- neg_binomial_2_log(d_int, p_vector, d_real);
  transformed_param_real <- neg_binomial_2_log(d_int, p_vector, d_real_array);
  transformed_param_real <- neg_binomial_2_log(d_int, p_vector, d_vector);
  transformed_param_real <- neg_binomial_2_log(d_int, p_vector, d_row_vector);
  transformed_param_real <- neg_binomial_2_log(d_int, p_vector, p_real);
  transformed_param_real <- neg_binomial_2_log(d_int, p_vector, p_real_array);
  transformed_param_real <- neg_binomial_2_log(d_int, p_vector, p_vector);
  transformed_param_real <- neg_binomial_2_log(d_int, p_vector, p_row_vector);
  transformed_param_real <- neg_binomial_2_log(d_int, p_row_vector, d_int);
  transformed_param_real <- neg_binomial_2_log(d_int, p_row_vector, d_real);
  transformed_param_real <- neg_binomial_2_log(d_int, p_row_vector, d_real_array);
  transformed_param_real <- neg_binomial_2_log(d_int, p_row_vector, d_vector);
  transformed_param_real <- neg_binomial_2_log(d_int, p_row_vector, d_row_vector);
  transformed_param_real <- neg_binomial_2_log(d_int, p_row_vector, p_real);
  transformed_param_real <- neg_binomial_2_log(d_int, p_row_vector, p_real_array);
  transformed_param_real <- neg_binomial_2_log(d_int, p_row_vector, p_vector);
  transformed_param_real <- neg_binomial_2_log(d_int, p_row_vector, p_row_vector);
  transformed_param_real <- neg_binomial_2_log(d_int_array, d_int, d_int);
  transformed_param_real <- neg_binomial_2_log(d_int_array, d_int, d_real);
  transformed_param_real <- neg_binomial_2_log(d_int_array, d_int, d_real_array);
  transformed_param_real <- neg_binomial_2_log(d_int_array, d_int, d_vector);
  transformed_param_real <- neg_binomial_2_log(d_int_array, d_int, d_row_vector);
  transformed_param_real <- neg_binomial_2_log(d_int_array, d_int, p_real);
  transformed_param_real <- neg_binomial_2_log(d_int_array, d_int, p_real_array);
  transformed_param_real <- neg_binomial_2_log(d_int_array, d_int, p_vector);
  transformed_param_real <- neg_binomial_2_log(d_int_array, d_int, p_row_vector);
  transformed_param_real <- neg_binomial_2_log(d_int_array, d_real, d_int);
  transformed_param_real <- neg_binomial_2_log(d_int_array, d_real, d_real);
  transformed_param_real <- neg_binomial_2_log(d_int_array, d_real, d_real_array);
  transformed_param_real <- neg_binomial_2_log(d_int_array, d_real, d_vector);
  transformed_param_real <- neg_binomial_2_log(d_int_array, d_real, d_row_vector);
  transformed_param_real <- neg_binomial_2_log(d_int_array, d_real, p_real);
  transformed_param_real <- neg_binomial_2_log(d_int_array, d_real, p_real_array);
  transformed_param_real <- neg_binomial_2_log(d_int_array, d_real, p_vector);
  transformed_param_real <- neg_binomial_2_log(d_int_array, d_real, p_row_vector);
  transformed_param_real <- neg_binomial_2_log(d_int_array, d_real_array, d_int);
  transformed_param_real <- neg_binomial_2_log(d_int_array, d_real_array, d_real);
  transformed_param_real <- neg_binomial_2_log(d_int_array, d_real_array, d_real_array);
  transformed_param_real <- neg_binomial_2_log(d_int_array, d_real_array, d_vector);
  transformed_param_real <- neg_binomial_2_log(d_int_array, d_real_array, d_row_vector);
  transformed_param_real <- neg_binomial_2_log(d_int_array, d_real_array, p_real);
  transformed_param_real <- neg_binomial_2_log(d_int_array, d_real_array, p_real_array);
  transformed_param_real <- neg_binomial_2_log(d_int_array, d_real_array, p_vector);
  transformed_param_real <- neg_binomial_2_log(d_int_array, d_real_array, p_row_vector);
  transformed_param_real <- neg_binomial_2_log(d_int_array, d_vector, d_int);
  transformed_param_real <- neg_binomial_2_log(d_int_array, d_vector, d_real);
  transformed_param_real <- neg_binomial_2_log(d_int_array, d_vector, d_real_array);
  transformed_param_real <- neg_binomial_2_log(d_int_array, d_vector, d_vector);
  transformed_param_real <- neg_binomial_2_log(d_int_array, d_vector, d_row_vector);
  transformed_param_real <- neg_binomial_2_log(d_int_array, d_vector, p_real);
  transformed_param_real <- neg_binomial_2_log(d_int_array, d_vector, p_real_array);
  transformed_param_real <- neg_binomial_2_log(d_int_array, d_vector, p_vector);
  transformed_param_real <- neg_binomial_2_log(d_int_array, d_vector, p_row_vector);
  transformed_param_real <- neg_binomial_2_log(d_int_array, d_row_vector, d_int);
  transformed_param_real <- neg_binomial_2_log(d_int_array, d_row_vector, d_real);
  transformed_param_real <- neg_binomial_2_log(d_int_array, d_row_vector, d_real_array);
  transformed_param_real <- neg_binomial_2_log(d_int_array, d_row_vector, d_vector);
  transformed_param_real <- neg_binomial_2_log(d_int_array, d_row_vector, d_row_vector);
  transformed_param_real <- neg_binomial_2_log(d_int_array, d_row_vector, p_real);
  transformed_param_real <- neg_binomial_2_log(d_int_array, d_row_vector, p_real_array);
  transformed_param_real <- neg_binomial_2_log(d_int_array, d_row_vector, p_vector);
  transformed_param_real <- neg_binomial_2_log(d_int_array, d_row_vector, p_row_vector);
  transformed_param_real <- neg_binomial_2_log(d_int_array, p_real, d_int);
  transformed_param_real <- neg_binomial_2_log(d_int_array, p_real, d_real);
  transformed_param_real <- neg_binomial_2_log(d_int_array, p_real, d_real_array);
  transformed_param_real <- neg_binomial_2_log(d_int_array, p_real, d_vector);
  transformed_param_real <- neg_binomial_2_log(d_int_array, p_real, d_row_vector);
  transformed_param_real <- neg_binomial_2_log(d_int_array, p_real, p_real);
  transformed_param_real <- neg_binomial_2_log(d_int_array, p_real, p_real_array);
  transformed_param_real <- neg_binomial_2_log(d_int_array, p_real, p_vector);
  transformed_param_real <- neg_binomial_2_log(d_int_array, p_real, p_row_vector);
  transformed_param_real <- neg_binomial_2_log(d_int_array, p_real_array, d_int);
  transformed_param_real <- neg_binomial_2_log(d_int_array, p_real_array, d_real);
  transformed_param_real <- neg_binomial_2_log(d_int_array, p_real_array, d_real_array);
  transformed_param_real <- neg_binomial_2_log(d_int_array, p_real_array, d_vector);
  transformed_param_real <- neg_binomial_2_log(d_int_array, p_real_array, d_row_vector);
  transformed_param_real <- neg_binomial_2_log(d_int_array, p_real_array, p_real);
  transformed_param_real <- neg_binomial_2_log(d_int_array, p_real_array, p_real_array);
  transformed_param_real <- neg_binomial_2_log(d_int_array, p_real_array, p_vector);
  transformed_param_real <- neg_binomial_2_log(d_int_array, p_real_array, p_row_vector);
  transformed_param_real <- neg_binomial_2_log(d_int_array, p_vector, d_int);
  transformed_param_real <- neg_binomial_2_log(d_int_array, p_vector, d_real);
  transformed_param_real <- neg_binomial_2_log(d_int_array, p_vector, d_real_array);
  transformed_param_real <- neg_binomial_2_log(d_int_array, p_vector, d_vector);
  transformed_param_real <- neg_binomial_2_log(d_int_array, p_vector, d_row_vector);
  transformed_param_real <- neg_binomial_2_log(d_int_array, p_vector, p_real);
  transformed_param_real <- neg_binomial_2_log(d_int_array, p_vector, p_real_array);
  transformed_param_real <- neg_binomial_2_log(d_int_array, p_vector, p_vector);
  transformed_param_real <- neg_binomial_2_log(d_int_array, p_vector, p_row_vector);
  transformed_param_real <- neg_binomial_2_log(d_int_array, p_row_vector, d_int);
  transformed_param_real <- neg_binomial_2_log(d_int_array, p_row_vector, d_real);
  transformed_param_real <- neg_binomial_2_log(d_int_array, p_row_vector, d_real_array);
  transformed_param_real <- neg_binomial_2_log(d_int_array, p_row_vector, d_vector);
  transformed_param_real <- neg_binomial_2_log(d_int_array, p_row_vector, d_row_vector);
  transformed_param_real <- neg_binomial_2_log(d_int_array, p_row_vector, p_real);
  transformed_param_real <- neg_binomial_2_log(d_int_array, p_row_vector, p_real_array);
  transformed_param_real <- neg_binomial_2_log(d_int_array, p_row_vector, p_vector);
  transformed_param_real <- neg_binomial_2_log(d_int_array, p_row_vector, p_row_vector);
}
model {  
  y_p ~ normal(0,1); // in case anyone tries to run it

  d_int ~ neg_binomial_2(p_real, d_int);
  d_int ~ neg_binomial_2(p_real, p_real);
  d_int ~ neg_binomial_2(p_real, p_real_array);
  d_int ~ neg_binomial_2(p_real, p_vector);
  d_int ~ neg_binomial_2(p_real, p_row_vector);
  d_int ~ neg_binomial_2(p_real, d_real);
  d_int ~ neg_binomial_2(p_real, d_real_array);
  d_int ~ neg_binomial_2(p_real, d_vector);
  d_int ~ neg_binomial_2(p_real, d_row_vector);
  d_int ~ neg_binomial_2(d_real, d_int);
  d_int ~ neg_binomial_2(d_real, p_real);
  d_int ~ neg_binomial_2(d_real, p_real_array);
  d_int ~ neg_binomial_2(d_real, p_vector);
  d_int ~ neg_binomial_2(d_real, p_row_vector);
  d_int ~ neg_binomial_2(d_real, d_real);
  d_int ~ neg_binomial_2(d_real, d_real_array);
  d_int ~ neg_binomial_2(d_real, d_vector);
  d_int ~ neg_binomial_2(d_real, d_row_vector);

  d_int ~ neg_binomial_2(d_int, d_int);
  d_int ~ neg_binomial_2(d_int, p_real);
  d_int ~ neg_binomial_2(d_int, p_real_array);
  d_int ~ neg_binomial_2(d_int, p_vector);
  d_int ~ neg_binomial_2(d_int, p_row_vector);
  d_int ~ neg_binomial_2(d_int, d_real);
  d_int ~ neg_binomial_2(d_int, d_real_array);
  d_int ~ neg_binomial_2(d_int, d_vector);
  d_int ~ neg_binomial_2(d_int, d_row_vector);

  d_int ~ neg_binomial_2(p_real_array, d_int);
  d_int ~ neg_binomial_2(p_real_array, p_real);
  d_int ~ neg_binomial_2(p_real_array, p_real_array);
  d_int ~ neg_binomial_2(p_real_array, p_vector);
  d_int ~ neg_binomial_2(p_real_array, p_row_vector);
  d_int ~ neg_binomial_2(p_real_array, d_real);
  d_int ~ neg_binomial_2(p_real_array, d_real_array);
  d_int ~ neg_binomial_2(p_real_array, d_vector);
  d_int ~ neg_binomial_2(p_real_array, d_row_vector);
  d_int ~ neg_binomial_2(d_real_array, d_int);
  d_int ~ neg_binomial_2(d_real_array, p_real);
  d_int ~ neg_binomial_2(d_real_array, p_real_array);
  d_int ~ neg_binomial_2(d_real_array, p_vector);
  d_int ~ neg_binomial_2(d_real_array, p_row_vector);
  d_int ~ neg_binomial_2(d_real_array, d_real);
  d_int ~ neg_binomial_2(d_real_array, d_real_array);
  d_int ~ neg_binomial_2(d_real_array, d_vector);
  d_int ~ neg_binomial_2(d_real_array, d_row_vector);

  d_int ~ neg_binomial_2(p_vector, d_int);
  d_int ~ neg_binomial_2(p_vector, p_real);
  d_int ~ neg_binomial_2(p_vector, p_real_array);
  d_int ~ neg_binomial_2(p_vector, p_vector);
  d_int ~ neg_binomial_2(p_vector, p_row_vector);
  d_int ~ neg_binomial_2(p_vector, d_real);
  d_int ~ neg_binomial_2(p_vector, d_real_array);
  d_int ~ neg_binomial_2(p_vector, d_vector);
  d_int ~ neg_binomial_2(p_vector, d_row_vector);
  d_int ~ neg_binomial_2(d_vector, d_int);
  d_int ~ neg_binomial_2(d_vector, p_real);
  d_int ~ neg_binomial_2(d_vector, p_real_array);
  d_int ~ neg_binomial_2(d_vector, p_vector);
  d_int ~ neg_binomial_2(d_vector, p_row_vector);
  d_int ~ neg_binomial_2(d_vector, d_real);
  d_int ~ neg_binomial_2(d_vector, d_real_array);
  d_int ~ neg_binomial_2(d_vector, d_vector);
  d_int ~ neg_binomial_2(d_vector, d_row_vector);

  d_int ~ neg_binomial_2(p_row_vector, d_int);
  d_int ~ neg_binomial_2(p_row_vector, p_real);
  d_int ~ neg_binomial_2(p_row_vector, p_real_array);
  d_int ~ neg_binomial_2(p_row_vector, p_vector);
  d_int ~ neg_binomial_2(p_row_vector, p_row_vector);
  d_int ~ neg_binomial_2(p_row_vector, d_real);
  d_int ~ neg_binomial_2(p_row_vector, d_real_array);
  d_int ~ neg_binomial_2(p_row_vector, d_vector);
  d_int ~ neg_binomial_2(p_row_vector, d_row_vector);
  d_int ~ neg_binomial_2(d_row_vector, d_int);
  d_int ~ neg_binomial_2(d_row_vector, p_real);
  d_int ~ neg_binomial_2(d_row_vector, p_real_array);
  d_int ~ neg_binomial_2(d_row_vector, p_vector);
  d_int ~ neg_binomial_2(d_row_vector, p_row_vector);
  d_int ~ neg_binomial_2(d_row_vector, d_real);
  d_int ~ neg_binomial_2(d_row_vector, d_real_array);
  d_int ~ neg_binomial_2(d_row_vector, d_vector);
  d_int ~ neg_binomial_2(d_row_vector, d_row_vector);

  d_int_array ~ neg_binomial_2(p_real, d_int);
  d_int_array ~ neg_binomial_2(p_real, p_real);
  d_int_array ~ neg_binomial_2(p_real, p_real_array);
  d_int_array ~ neg_binomial_2(p_real, p_vector);
  d_int_array ~ neg_binomial_2(p_real, p_row_vector);
  d_int_array ~ neg_binomial_2(p_real, d_real);
  d_int_array ~ neg_binomial_2(p_real, d_real_array);
  d_int_array ~ neg_binomial_2(p_real, d_vector);
  d_int_array ~ neg_binomial_2(p_real, d_row_vector);
  d_int_array ~ neg_binomial_2(d_real, d_int);
  d_int_array ~ neg_binomial_2(d_real, p_real);
  d_int_array ~ neg_binomial_2(d_real, p_real_array);
  d_int_array ~ neg_binomial_2(d_real, p_vector);
  d_int_array ~ neg_binomial_2(d_real, p_row_vector);
  d_int_array ~ neg_binomial_2(d_real, d_real);
  d_int_array ~ neg_binomial_2(d_real, d_real_array);
  d_int_array ~ neg_binomial_2(d_real, d_vector);
  d_int_array ~ neg_binomial_2(d_real, d_row_vector);

  d_int_array ~ neg_binomial_2(d_int, d_int);
  d_int_array ~ neg_binomial_2(d_int, p_real);
  d_int_array ~ neg_binomial_2(d_int, p_real_array);
  d_int_array ~ neg_binomial_2(d_int, p_vector);
  d_int_array ~ neg_binomial_2(d_int, p_row_vector);
  d_int_array ~ neg_binomial_2(d_int, d_real);
  d_int_array ~ neg_binomial_2(d_int, d_real_array);
  d_int_array ~ neg_binomial_2(d_int, d_vector);
  d_int_array ~ neg_binomial_2(d_int, d_row_vector);

  d_int_array ~ neg_binomial_2(p_real_array, d_int);
  d_int_array ~ neg_binomial_2(p_real_array, p_real);
  d_int_array ~ neg_binomial_2(p_real_array, p_real_array);
  d_int_array ~ neg_binomial_2(p_real_array, p_vector);
  d_int_array ~ neg_binomial_2(p_real_array, p_row_vector);
  d_int_array ~ neg_binomial_2(p_real_array, d_real);
  d_int_array ~ neg_binomial_2(p_real_array, d_real_array);
  d_int_array ~ neg_binomial_2(p_real_array, d_vector);
  d_int_array ~ neg_binomial_2(p_real_array, d_row_vector);
  d_int_array ~ neg_binomial_2(d_real_array, d_int);
  d_int_array ~ neg_binomial_2(d_real_array, p_real);
  d_int_array ~ neg_binomial_2(d_real_array, p_real_array);
  d_int_array ~ neg_binomial_2(d_real_array, p_vector);
  d_int_array ~ neg_binomial_2(d_real_array, p_row_vector);
  d_int_array ~ neg_binomial_2(d_real_array, d_real);
  d_int_array ~ neg_binomial_2(d_real_array, d_real_array);
  d_int_array ~ neg_binomial_2(d_real_array, d_vector);
  d_int_array ~ neg_binomial_2(d_real_array, d_row_vector);

  d_int_array ~ neg_binomial_2(p_vector, d_int);
  d_int_array ~ neg_binomial_2(p_vector, p_real);
  d_int_array ~ neg_binomial_2(p_vector, p_real_array);
  d_int_array ~ neg_binomial_2(p_vector, p_vector);
  d_int_array ~ neg_binomial_2(p_vector, p_row_vector);
  d_int_array ~ neg_binomial_2(p_vector, d_real);
  d_int_array ~ neg_binomial_2(p_vector, d_real_array);
  d_int_array ~ neg_binomial_2(p_vector, d_vector);
  d_int_array ~ neg_binomial_2(p_vector, d_row_vector);
  d_int_array ~ neg_binomial_2(d_vector, d_int);
  d_int_array ~ neg_binomial_2(d_vector, p_real);
  d_int_array ~ neg_binomial_2(d_vector, p_real_array);
  d_int_array ~ neg_binomial_2(d_vector, p_vector);
  d_int_array ~ neg_binomial_2(d_vector, p_row_vector);
  d_int_array ~ neg_binomial_2(d_vector, d_real);
  d_int_array ~ neg_binomial_2(d_vector, d_real_array);
  d_int_array ~ neg_binomial_2(d_vector, d_vector);
  d_int_array ~ neg_binomial_2(d_vector, d_row_vector);

  d_int_array ~ neg_binomial_2(p_row_vector, d_int);
  d_int_array ~ neg_binomial_2(p_row_vector, p_real);
  d_int_array ~ neg_binomial_2(p_row_vector, p_real_array);
  d_int_array ~ neg_binomial_2(p_row_vector, p_vector);
  d_int_array ~ neg_binomial_2(p_row_vector, p_row_vector);
  d_int_array ~ neg_binomial_2(p_row_vector, d_real);
  d_int_array ~ neg_binomial_2(p_row_vector, d_real_array);
  d_int_array ~ neg_binomial_2(p_row_vector, d_vector);
  d_int_array ~ neg_binomial_2(p_row_vector, d_row_vector);
  d_int_array ~ neg_binomial_2(d_row_vector, d_int);
  d_int_array ~ neg_binomial_2(d_row_vector, p_real);
  d_int_array ~ neg_binomial_2(d_row_vector, p_real_array);
  d_int_array ~ neg_binomial_2(d_row_vector, p_vector);
  d_int_array ~ neg_binomial_2(d_row_vector, p_row_vector);
  d_int_array ~ neg_binomial_2(d_row_vector, d_real);
  d_int_array ~ neg_binomial_2(d_row_vector, d_real_array);
  d_int_array ~ neg_binomial_2(d_row_vector, d_vector);
  d_int_array ~ neg_binomial_2(d_row_vector, d_row_vector);
}
